# Generated by Django 4.1.5 on 2023-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='accuracy',
            field=models.FloatField(default=100.0),
        ),
    ]
